BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `statistics` (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"user_id"	INTEGER NOT NULL,
	"begin_online"	REAL DEFAULT NULL,
	"end_online"	REAL DEFAULT NULL,
	"platform"		INTEGER DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `vk_users` (
	"id"		INTEGER PRIMARY KEY AUTOINCREMENT,
	"user_id" 	INTEGER NOT NULL,
	"full_name" TEXT
);
COMMIT;
