BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `statistics` (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"user_id"	INTEGER NOT NULL,
	"begin_online"	REAL DEFAULT NULL,
	"end_online"	REAL DEFAULT NULL
);
COMMIT;
